### ISSUE TITLE
Referring to a static method of a class causes an error

### ISSUE THREAD

**Issue by chrisrink10** [chrisrink10/basilisp#371]
In Clojure, everything is a either an unqualified name or a fully qualified name, so this problem would not occur. However, in Basilisp the distinction between modules, classes, and locals is muddier. As a result, something which should obviously work, doesn't:

```
user=> (basilisp.lang.map.MapEntry/of :a 1)
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 159, in repl
    result = eval_str(lsrc, ctx, ns.module, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 75, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, module)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 107, in compile_and_exec_form
    lisp_ast = parse_ast(ctx.parser_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2166, in parse_ast
    return _parse_ast(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 456, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2109, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1785, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1352, in _invoke_ast
    fn = _parse_ast(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 456, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2123, in _parse_ast
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1949, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1927, in _resolve_sym
    return __resolve_namespaced_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1875, in __resolve_namespaced_symbol
    f"unable to resolve symbol '{form}' in this context", form=form
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'basilisp.lang.map.MapEntry/of' in this context
```

**Comment by chrisrink10** [comment]
As a workaround, you can use `((.-of basilisp.lang.map.MapEntry) :a 1)`, but that's harder to read and fairly implementation specific.
